# Generated by Django 6.0.2 on 2026-04-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_attendance_student_remove_attendance_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student',
            new_name='user',
        ),
    ]
