# Generated by Django 6.0.2 on 2026-03-26 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('xp_points', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('track_name', models.CharField(default='Backend Dev', max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('previous_rank', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-xp_points'],
            },
        ),
    ]
