# Generated by Django 6.0.2 on 2026-04-10 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('target_role', models.CharField(blank=True, choices=[('backend', 'Backend Developer'), ('frontend', 'Frontend Developer'), ('fullstack', 'Full Stack Developer'), ('ml', 'ML Engineer'), ('devops', 'DevOps Engineer')], max_length=20)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('portfolio', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
