# Generated by Django 6.0.2 on 2026-04-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_role',
            field=models.CharField(blank=True, choices=[('backend', 'Backend Developer'), ('frontend', 'Frontend Developer'), ('fullstack', 'Full Stack Developer'), ('ml', 'ML Engineer'), ('devops', 'DevOps Engineer')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
